version: '3'

services: 
  db:
    image: postgres
    restart: always
    tty: true
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Meriva01
      - POSTGRES_DB=golang
    ports: 
      - "5434:5432"
      